use cube::*;

#[test]
fn it_can_rotate_yellow_clockwise() {
    let mut cube = Cube::new();
    cube.rotate_yellow_cw();
    assert_eq!(
        vec![
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
            Color::Yellow,
        ],
        cube.yellow
    );
    assert_eq!(
        vec![
            Color::Green,
            Color::Green,
            Color::Green,
            Color::Red,
            Color::Red,
            Color::Red,
            Color::Red,
            Color::Red,
            Color::Red,
        ],
        cube.red
    );
    assert_eq!(
        vec![
            Color::Orange,
            Color::Orange,
            Color::Orange,
            Color::Green,
            Color::Green,
            Color::Green,
            Color::Green,
            Color::Green,
            Color::Green,
        ],
        cube.green
    );
    assert_eq!(
        vec![
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Orange,
            Color::Orange,
            Color::Orange,
            Color::Orange,
            Color::Orange,
            Color::Orange,
        ],
        cube.orange
    );
    assert_eq!(
        vec![
            Color::Red,
            Color::Red,
            Color::Red,
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Blue,
        ],
        cube.blue
    );
    assert_eq!(
        vec![
            Color::Red,
            Color::Red,
            Color::Red,
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Blue,
            Color::Blue,
        ],
        cube.blue
    );
    assert_eq!(
        vec![
            Color::White,
            Color::White,
            Color::White,
            Color::White,
            Color::White,
            Color::White,
            Color::White,
            Color::White,
            Color::White,
        ],
        cube.white
    );
}
